[platformio]
default_envs = m5dial

[env:m5dial]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; C++標準指定（M5Siv3DはC++17機能を使用）
build_unflags =
    -std=gnu++11

; M5Unified ライブラリの依存関係
lib_deps = 
    m5stack/M5Unified@^0.2.11
    m5stack/M5Dial@^1.0.2
    Densaugeo/base64

; ビルドフラグ
build_flags = 
    -DUSE_M5_DIAL
    -DCORE_DEBUG_LEVEL=3
    -std=gnu++17

; アップロード設定
upload_speed = 921600
upload_port = COM9
monitor_speed = 115200
monitor_port = COM9
